### ISSUE TITLE
support storing multiple decoders?

### ISSUE THREAD

**Issue by jonasohland** [smp-3d/dotadd#1]
[This](http://www.ifc18.uni-mainz.de/papers/heller.pdf) paper discusses the design and implementation of psychoacoustic filters for ambisonic decoding. To support 

> - Phase-matched, band-splitting filters to enable the use of separate low- and high-frequency decoding matrices, sup- porting the duplex theory of human directional hearing
> - Per-speaker, near-field compensation due to the fact that most Ambisonic decoder design techniques assume the su- perposition of plane waves, whereas the loudspeakers are actually at a finite distance and radiating spherical waves
> - Optional delay and level compensation to accommodate loudspeakers at varying distances from the center of the ar- ray

For the first filtering application two separate decoding matrices are used. So, should we support 1 + n matrices for a single .add file and add additional Metadata or an unspecified user-data field to each matrix?

**Comment by HenningSchaar** [comment]
The Band-Splitting filters could be as you suggested saved in a second matrix, but we have to define the crossover function and crossover point. So there has to be at least two additional data fields right?

- Is there a band-splitting filter
- Where is the Crossover
(-which crossover function is being used?)

For the NFC Filters I don't really understand how we would store these in the .add json.

Delay and Gain compensation could easily be infered from the radius stored in the speaker information. (ɸ, θ, r) This could be done by the software library.
